name: First github action

on:
  push:
    branches: main
    
jobs:
  test:
    name: Make a pull
    runs-on: ubuntu-latest
    
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_SECRET }}
          known_hosts: unnecessary
      
      - name: Adding Known Hosts
#        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        run: |
          cd ~/.ssh
          rm ./known_hosts
          ls
          ssh-keyscan -H 192.168.100.174
      
#       name: Deploy with rsync
#        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:C:\Users\DIICA\.ssh\tmp
